version: '3'
services:
  isens-bot:
    build: .
    image: isens-bot:latest
    container_name: isens-bot
    restart: always
    volumes:
      - ./config.json:/app/config.json
      - ./state.json:/app/state.json
    environment:
      - TZ=Asia/Seoul
